-- Build Save/Load Manager
-- Handles saving and loading custom skill configurations
-- Adds small ImGui in-game import UI (optional), console fallbacks, and a file-bridge import helper for Overwolf

-- Safe require for importer (optional)
local _ok_importer, build_importer = pcall(require, "build_importer")
if not _ok_importer then
    if console and console.print then console.print("Warning: build_importer module not found; import features limited") end
    build_importer = nil
end

-- try to get imgui (some environments expose it as global `imgui` or as a module)
local imgui = nil
do
    local ok, mod = pcall(require, "imgui")
    if ok and mod then imgui = mod end
    if not imgui and _G.imgui then imgui = _G.imgui end
    if not imgui and console and console.print then console.print("ImGui not found; in-game UI disabled (use prompt-based import)") end
end

local build_saver = {}

-- File path for saved builds (Lua formatted)
local save_file_path = "paladin_saved_builds.lua"

-- Saved builds storage
local saved_builds = {}

-- Spells table reference (set by your main script)
local spells_table_ref = nil
function build_saver.set_spells_table(spells)
    spells_table_ref = spells
end

-- Initialize saved builds
local function initialize_saved_builds()
    if not saved_builds or type(saved_builds) ~= "table" then
        saved_builds = {}
    end
end

-- Helper: serialize table to Lua code (handles strings, numbers, booleans, and nested tables)
local function serialize_table(tbl, indent)
    indent = indent or 0
    local ind = string.rep("  ", indent)
    local parts = {}
    table.insert(parts, "{\n")
    for k, v in pairs(tbl) do
        local key_repr = "[" .. string.format("%q", tostring(k)) .. "]"
        local value_repr
        if type(v) == "table" then
            value_repr = serialize_table(v, indent + 1)
        elseif type(v) == "string" then
            value_repr = string.format("%q", v)
        elseif type(v) == "number" or type(v) == "boolean" then
            value_repr = tostring(v)
        else
            value_repr = string.format("%q", tostring(v))
        end
        table.insert(parts, ind .. "  " .. key_repr .. " = " .. value_repr .. ",\n")
    end
    table.insert(parts, ind .. "}")
    return table.concat(parts)
end

-- Save builds to file (Lua format)
function build_saver.save_to_file()
    initialize_saved_builds()

    local file, err = io.open(save_file_path, "w")
    if not file then
        return false, "Could not open file for writing: " .. tostring(err)
    end

    if console and console.print then console.print("DEBUG: Saving builds to file (Lua format)...") end

    local ok, serialized = pcall(function() return "return " .. serialize_table(saved_builds) end)
    if not ok or not serialized then
        file:close()
        return false, "Failed to serialize builds"
    end

    file:write("-- paladin_saved_builds.lua - generated by build_saver\n")
    file:write("-- DO NOT EDIT UNLESS YOU KNOW WHAT YOU'RE DOING\n\n")
    file:write(serialized)
    file:write("\n")
    file:close()

    if console and console.print then console.print("DEBUG: File saved successfully to " .. save_file_path) end
    return true, "Builds saved to file"
end

-- Load builds from file (Lua format preferred)
function build_saver.load_from_file()
    local chunk, load_err = loadfile(save_file_path)
    if not chunk then
        initialize_saved_builds()
        if console and console.print then console.print("DEBUG: No saved builds file found or failed to load: " .. tostring(load_err)) end
        return false, "No saved builds file found, starting fresh"
    end

    local ok, result = pcall(chunk)
    if ok and type(result) == "table" then
        saved_builds = result
        if console and console.print then console.print("DEBUG: Loaded saved builds from Lua file. Builds found: " .. tostring((function() local n=0; for _ in pairs(saved_builds) do n=n+1 end; return n end)())) end
        initialize_saved_builds()
        return true, "Builds loaded from file (Lua format)"
    end

    initialize_saved_builds()
    return false, "Could not parse saved builds file; starting fresh"
end

-- Save current skill configuration
function build_saver.save_current_build(build_name, spells_table)
    initialize_saved_builds()

    if not build_name or build_name == "" then
        return false, "Build name cannot be empty"
    end

    local now = os.time()
    local build_config = {
        name = build_name,
        skills = {},
        created_at = now,
        updated_at = now
    }

    if saved_builds[build_name] and saved_builds[build_name].created_at then
        build_config.created_at = saved_builds[build_name].created_at
    end

    local enabled_skill_count = 0
    for spell_name, spell_module in pairs(spells_table) do
        if spell_module and spell_module.get_enabled then
            local ok, is_enabled = pcall(spell_module.get_enabled)
            if ok and is_enabled then
                build_config.skills[spell_name] = { enabled = true }
                enabled_skill_count = enabled_skill_count + 1
                if console and console.print then console.print("Saved " .. spell_name .. ": " .. tostring(is_enabled)) end
            end
        end
    end

    if console and console.print then console.print("Total enabled skills saved: " .. enabled_skill_count) end

    -- Only replace/add this build; do not wipe others
    saved_builds[build_name] = build_config

    -- Save to file
    local success, message = build_saver.save_to_file()
    if success then
        return true, "Build '" .. build_name .. "' saved successfully! (" .. enabled_skill_count .. " enabled skills)"
    else
        return false, message
    end
end

-- Load saved build configuration
function build_saver.load_build(build_name, spells_table)
    initialize_saved_builds()

    if not saved_builds[build_name] then
        if console and console.print then
            console.print("DEBUG: Build '" .. tostring(build_name) .. "' not found in memory")
            local names = build_saver.get_saved_build_names()
            console.print("DEBUG: Available builds in memory: " .. table.concat(names, ", "))
        end
        return false, "Build '" .. tostring(build_name) .. "' not found"
    end

    local build_config = saved_builds[build_name]
    local skill_count = 0

    if console and console.print then console.print("Loading build: " .. build_name) end

    -- Count skills properly
    local actual_skill_count = 0
    for _ in pairs(build_config.skills) do actual_skill_count = actual_skill_count + 1 end
    if console and console.print then console.print("DEBUG: Actual skill count: " .. actual_skill_count) end

    -- First disable ALL skills to ensure clean state
    if console and console.print then console.print("Disabling all skills first...") end
    local total_skills_disabled = 0
    for spell_name, spell_module in pairs(spells_table) do
        if spell_module and spell_module.set_enabled and spell_module.get_enabled then
            local was_enabled = false
            local ok, state = pcall(spell_module.get_enabled)
            if ok and state then was_enabled = true end
            pcall(function() spell_module.set_enabled(false) end)
            if was_enabled then
                total_skills_disabled = total_skills_disabled + 1
                if console and console.print then console.print("  Disabled " .. spell_name) end
            end
        end
    end
    if console and console.print then console.print("Disabled " .. total_skills_disabled .. " skills that were enabled") end

    -- Then enable only the skills in the saved build
    if console and console.print then console.print("Enabling saved skills...") end
    for spell_name, skill_data in pairs(build_config.skills) do
        if spells_table[spell_name] then
            local spell_module = spells_table[spell_name]
            if spell_module.set_enabled then
                pcall(function() spell_module.set_enabled(skill_data.enabled) end)
                skill_count = skill_count + 1
                if console and console.print then console.print("Loaded " .. spell_name .. ": " .. tostring(skill_data.enabled)) end
                if spell_module.get_enabled then
                    local ok, current_state = pcall(spell_module.get_enabled)
                    if ok and current_state ~= skill_data.enabled then
                        if console and console.print then console.print("WARNING: " .. spell_name .. " should be " .. tostring(skill_data.enabled) .. " but is " .. tostring(current_state)) end
                    end
                end
            else
                if console and console.print then console.print("Warning: Could not set " .. spell_name .. " (no set_enabled function)") end
            end
        else
            if console and console.print then console.print("Warning: Spell " .. spell_name .. " not found in current spells table") end
        end
    end

    if console and console.print then console.print("Total skills loaded: " .. skill_count) end
    return true, "Build '" .. build_name .. "' loaded successfully! (" .. skill_count .. " skills)"
end

-- Get list of saved build names
function build_saver.get_saved_build_names()
    initialize_saved_builds()
    local names = {}
    for name, _ in pairs(saved_builds) do
        table.insert(names, name)
    end
    table.sort(names)
    return names
end

-- Delete a saved build
function build_saver.delete_build(build_name)
    initialize_saved_builds()

    if not saved_builds[build_name] then
        return false, "Build '" .. build_name .. "' not found"
    end

    saved_builds[build_name] = nil

    -- Save to file
    local success, message = build_saver.save_to_file()
    if success then
        return true, "Build '" .. build_name .. "' deleted successfully!"
    else
        return false, message
    end
end

-- Import a build from pasted text (uses build_importer if available)
function build_saver.import_build_from_string(import_text, target_name, spells_table)
    if not build_importer then
        return false, "Build importer not available (build_importer.lua missing)"
    end

    if not import_text or import_text == "" then
        return false, "No import text provided"
    end

    local parsed_skill_keys = build_importer.parse_import_text(import_text)
    if not parsed_skill_keys or #parsed_skill_keys == 0 then
        return false, "Could not parse any skills from import text"
    end

    -- Build config
    local now = os.time()
    local build_name = target_name or ("Imported_Build_" .. tostring(now))
    local build_config = {
        name = build_name,
        skills = {},
        created_at = now,
        updated_at = now
    }

    for _, skill_key in ipairs(parsed_skill_keys) do
        build_config.skills[skill_key] = { enabled = true }
    end

    saved_builds[build_name] = build_config
    local ok, msg = build_saver.save_to_file()
    if not ok then
        return false, "Parsed build created in memory, but failed to save to file: " .. tostring(msg)
    end

    -- Optionally apply to spells_table
    if spells_table then
        local _, load_msg = build_saver.load_build(build_name, spells_table)
        return true, "Imported and saved build '" .. build_name .. "'. " .. tostring(load_msg)
    end

    return true, "Imported and saved build '" .. build_name .. "' with " .. tostring(#parsed_skill_keys) .. " skills."
end

-- Utility: create a simple profile file for an imported build (best-effort)
function build_saver.write_profile_file(build_name)
    initialize_saved_builds()
    local build = saved_builds[build_name]
    if not build then
        return false, "Build not found: " .. tostring(build_name)
    end

    local safe_name = build_name:gsub("%s+", "_"):gsub("[^%w_%-]", "")
    local filename = safe_name .. "_profile.lua"
    local file, err = io.open(filename, "w")
    if not file then
        return false, "Could not write profile file: " .. tostring(err)
    end

    file:write("-- Auto-generated profile for build: " .. tostring(build_name) .. "\n")
    file:write("local profile = {\n")
    file:write("  name = " .. string.format("%q", build_name) .. ",\n")
    file:write("  description = " .. string.format("%q", "Imported profile") .. ",\n")
    file:write("  skills = {\n")
    for skill_name, skill_data in pairs(build.skills) do
        file:write("    [" .. string.format("%q", skill_name) .. "] = true,\n")
    end
    file:write("  }\n")
    file:write("}\n\n")
    file:write("local function apply(spells)\n")
    file:write("  for k, v in pairs(profile.skills) do\n")
    file:write("    if spells[k] and spells[k].set_enabled then\n")
    file:write("      spells[k].set_enabled(v)\n")
    file:write("    end\n")
    file:write("  end\n")
    file:write("end\n\n")
    file:write("return { profile = profile, apply = apply }\n")
    file:close()

    return true, "Profile file written: " .. filename
end

-- Console/UI helpers (prompt-based)
function build_saver.prompt_and_save(spells_table, prompt_text)
    prompt_text = prompt_text or "Enter build name to save:"
    if console and console.print then console.print(prompt_text) end
    local name = nil
    if io and io.read then
        io.write("> ")
        name = io.read()
    else
        return false, "No interactive input available. Call save_current_build(build_name, spells_table) directly."
    end
    return build_saver.save_current_build(name, spells_table)
end

function build_saver.prompt_and_load(spells_table, prompt_text)
    prompt_text = prompt_text or "Enter build name to load:"
    if console and console.print then console.print(prompt_text) end
    if io and io.read then
        io.write("> ")
        local name = io.read()
        return build_saver.load_build(name, spells_table)
    else
        return false, "No interactive input available. Call load_build(build_name, spells_table) directly."
    end
end

function build_saver.import_via_prompt(spells_table)
    local function safe_print(s) if console and console.print then console.print(s) else print(s) end end
    local function safe_read(prompt)
        safe_print(prompt)
        if io and io.read then
            io.write("> ")
            return io.read()
        end
        return nil
    end

    safe_print("Import helper: paste D4Build export, a skill list, or a D4Build share link.")
    local input = safe_read("Paste export text or link (or type 'cancel'):")

    if not input or input:lower() == "cancel" then
        return false, "Import cancelled"
    end

    input = input:gsub("^%s+", ""):gsub("%s+$", "")

    local d4build_id = string.match(input, "d4builds%.gg/builds/([%w%-]+)")
    if d4build_id then
        safe_print("Detected D4Build share link (id: " .. tostring(d4build_id) .. ").")
        safe_print("Open the link in your browser, use the site's Export/Copy, then paste the exported build text here.")
        local exported = safe_read("Now paste the exported build text from D4Build (or 'cancel'):")
        if not exported or exported:lower() == "cancel" then
            return false, "Import cancelled (no exported text provided)"
        end
        input = exported
    end

    local ok, msg = build_saver.import_build_from_string(input, nil, spells_table)
    if ok then
        safe_print("Import successful: " .. tostring(msg))
    else
        safe_print("Import failed: " .. tostring(msg))
        safe_print("Hints:")
        safe_print(" - If you pasted a D4Build link, use the page's Export/Copy and paste that exported text instead.")
        safe_print(" - You can paste a comma-separated or newline-separated list of skill names.")
    end

    return ok, msg
end

-- File-bridge import helpers for Overwolf / external paste workflow

-- Import from a plain text file. The file should contain the exported build text, or a comma/newline separated skill list.
-- If the file contains only a D4Build share link the function will return instructions (the script cannot fetch JS-rendered pages).
-- filename: path to file (relative to current working dir or absolute)
-- target_name: optional name for saved build (if nil a timestamp name is created)
-- spells_table: optional; if nil the stored spells_table_ref will be used
-- clear_after: boolean (default true) -- if true the file will be cleared after successful import
function build_saver.import_from_file(filename, target_name, spells_table, clear_after)
    clear_after = (clear_after == nil) and true or clear_after
    if not filename or filename == "" then
        return false, "No filename provided"
    end

    local f, err = io.open(filename, "r")
    if not f then
        return false, "Could not open file: " .. tostring(err)
    end

    local content = f:read("*a")
    f:close()
    if not content or content == "" then
        return false, "Import file is empty"
    end

    -- Trim whitespace
    content = content:gsub("^%s+", ""):gsub("%s+$", "")

    -- If file contains a share URL, instruct user to copy the exported text from the site
    local is_link = string.match(content, "d4builds%.gg/builds/[%w%-]+")
    if is_link then
        return false, "File contains a share link. Open that link in your browser and use Export/Copy on the D4Build page, then paste the exported text into the file."
    end

    -- choose spells table
    if not spells_table then spells_table = spells_table_ref end

    -- Use existing import_build_from_string
    local ok, msg = build_saver.import_build_from_string(content, target_name, spells_table)
    if ok and clear_after then
        -- clear the file so we don't import repeatedly
        local fw, ferr = io.open(filename, "w")
        if fw then fw:write("") fw:close() end
    end
    return ok, msg
end

-- Polling helper to call from your main loop (call it once per frame or at intervals)
-- It will attempt to import from filename if file contains content, then clear it (if auto_clear true).
-- Returns true, message on success or false, message on failure/no-action.
function build_saver.poll_import_file(filename, spells_table, auto_clear)
    auto_clear = (auto_clear == nil) and true or auto_clear
    local ok, err_or_msg = pcall(build_saver.import_from_file, filename, nil, spells_table, auto_clear)
    if not ok then
        return false, "Import failed: " .. tostring(err_or_msg)
    end
    return err_or_msg
end

-- Import UI (ImGui) state
local import_ui = {
    open = false,
    input_text = "",
    build_name = "",
    apply_immediately = true,
    create_profile_file = true,
    status_msg = ""
}

function build_saver.toggle_import_ui()
    import_ui.open = not import_ui.open
end

-- Draw the ImGui import window (call this every frame from your main loop)
function build_saver.draw_ui()
    if not imgui then return end
    if not import_ui.open then return end

    -- Begin window
    local ok_begin, _ = pcall(imgui.Begin, "Build Importer", true, imgui.WindowFlags or 0)
    if not ok_begin then return end

    -- Multiline input (try InputTextMultiline, else use InputText)
    do
        local success, a, b = pcall(function()
            if imgui.InputTextMultiline then
                return imgui.InputTextMultiline("Paste export / list / link", import_ui.input_text, 4096)
            else
                return imgui.InputText("Paste export / list / link", import_ui.input_text, 4096)
            end
        end)
        if success then
            if type(a) == "string" then import_ui.input_text = a
            elseif type(b) == "string" then import_ui.input_text = b
            end
        end
    end

    -- Build name input
    do
        local success, a, b = pcall(function()
            return imgui.InputText("Build name", import_ui.build_name, 256)
        end)
        if success then
            if type(a) == "string" then import_ui.build_name = a
            elseif type(b) == "string" then import_ui.build_name = b
            end
        end
    end

    -- Checkboxes: apply immediately / create profile
    do
        local ok1, changed1 = pcall(imgui.Checkbox, "Apply immediately", import_ui.apply_immediately)
        if ok1 and type(changed1) == "boolean" then import_ui.apply_immediately = changed1 end
        local ok2, changed2 = pcall(imgui.Checkbox, "Create profile file", import_ui.create_profile_file)
        if ok2 and type(changed2) == "boolean" then import_ui.create_profile_file = changed2 end
    end

    -- Buttons
    local import_clicked = false
    local cancel_clicked = false
    do
        local ok_import, pressed_import = pcall(imgui.Button, "Import")
        if ok_import and pressed_import then import_clicked = true end
        local ok_cancel, pressed_cancel = pcall(imgui.Button, "Cancel")
        if ok_cancel and pressed_cancel then cancel_clicked = true end
    end

    -- Status message
    if import_ui.status_msg and import_ui.status_msg ~= "" then
        pcall(imgui.TextWrapped, "Status: " .. import_ui.status_msg)
    end

    pcall(imgui.End)

    -- Handle button actions outside the window drawing to avoid nested ImGui calls
    if cancel_clicked then
        import_ui.open = false
        import_ui.status_msg = ""
        return
    end

    if import_clicked then
        local link_id = string.match(import_ui.input_text or "", "d4builds%.gg/builds/([%w%-]+)")
        if link_id then
            import_ui.status_msg = "Detected D4Build link. Open it in your browser and use Export/Copy, then paste the exported text here."
            return
        end

        if not build_importer then
            import_ui.status_msg = "Importer module missing (build_importer.lua)."
            return
        end

        local target_name = nil
        if import_ui.build_name and import_ui.build_name ~= "" then target_name = import_ui.build_name end

        local ok, msg = build_saver.import_build_from_string(import_ui.input_text, target_name, (import_ui.apply_immediately and spells_table_ref) and spells_table_ref or nil)
        if ok then
            import_ui.status_msg = "Import OK: " .. tostring(msg)
            if import_ui.create_profile_file and target_name then
                local ok2, msg2 = build_saver.write_profile_file(target_name)
                if ok2 then import_ui.status_msg = import_ui.status_msg .. " Profile written."
                else import_ui.status_msg = import_ui.status_msg .. " (Profile write failed: " .. tostring(msg2) .. ")"
                end
            end
        else
            import_ui.status_msg = "Import failed: " .. tostring(msg)
        end
    end
end

-- Convenience: print builds to console
function build_saver.print_saved_builds()
    initialize_saved_builds()
    local names = build_saver.get_saved_build_names()
    if #names == 0 then
        if console and console.print then console.print("No saved builds.") end
        return
    end
    if console and console.print then console.print("Saved builds:") end
    for _, name in ipairs(names) do
        local count = 0
        for _ in pairs(saved_builds[name].skills) do count = count + 1 end
        if console and console.print then console.print(" - " .. name .. " (" .. tostring(count) .. " skills)") end
    end
end

-- Initialization helper (call on addon start)
function build_saver.initialize()
    local ok, msg = build_saver.load_from_file()
    if not ok then
        if console and console.print then console.print("Build saver: " .. tostring(msg)) end
    else
        if console and console.print then console.print("Build saver loaded saved builds.") end
    end
end

-- Exports
return build_saver