-- import_runner.lua (enhanced: auto-name profiles, no "ImportedFromMobalytics")
-- Reads paladin_import.txt and supports multiple profile blocks.
-- Recognizes headers:
--   Profile: <Name>
--   [Name]
-- If no headers are present, tries to treat the first non-empty line as a profile name
-- when that line does NOT look like a skill name (best-effort using the provided spells table).
-- Otherwise the file is treated as a single profile and given an autogenerated name.
--
-- Usage:
-- - Place next to main.lua and keep require("import_runner") in main.lua (this module is non-blocking).
-- - Write paladin_import.txt using the formats discussed earlier.
-- - The importer will create saved builds with the profile names from your file.
--
-- Safety & behavior:
-- - Waits briefly for build_saver to be available (non-blocking).
-- - Writes a temporary file for each profile block and calls build_saver.import_from_file(temp, profile_name, spells).
-- - Clears paladin_import.txt after processing (so it won't re-import).
-- - Exposes concise console logging about imported profile names.
-- - Does NOT use or produce "ImportedFromMobalytics" as a name.

local IMPORT_FILE_PATH = [[C:\Users\pappi\OneDrive\Desktop\NWOO\scripts\rotation_paladin\paladin_import.txt]]
local TEMP_IMPORT_PATH   = [[C:\Users\pappi\OneDrive\Desktop\NWOO\scripts\rotation_paladin\paladin_import_tmp.txt]]
local MAX_ATTEMPTS = 12
local WAIT_SECONDS_BEFORE_START = 0.25

local attempts = 0
local started_at = (type(get_time_since_inject) == "function") and get_time_since_inject() or os.time()
local done = false

local function safe_print(msg)
    if type(console) == "table" and type(console.print) == "function" then
        pcall(console.print, tostring(msg))
    else
        pcall(print, tostring(msg))
    end
end

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil, "no file" end
    local content = f:read("*a")
    f:close()
    return content
end

local function write_file(path, content)
    local f, err = io.open(path, "w")
    if not f then return false, err end
    f:write(content or "")
    f:close()
    return true
end

local function clear_file(path)
    local ok, err = pcall(function() local f = io.open(path, "w"); if f then f:write(""); f:close(); end end)
    return ok, err
end

local function trim(s)
    if not s then return s end
    return (s:gsub("^%s*(.-)%s*$", "%1"))
end

local function normalize_string(s)
    if not s then return "" end
    s = s:lower()
    s = s:gsub("[%p]", " ")        -- replace punctuation with space
    s = s:gsub("%s+", " ")        -- collapse spaces
    s = trim(s)
    return s
end

local function build_skill_name_set(spells)
    -- Create a set of normalized candidate display names from the spells table.
    -- We attempt both "key -> readable" and any module.display_name if present.
    local set = {}
    if type(spells) ~= "table" then return set end
    for key, mod in pairs(spells) do
        -- form candidate from module display_name (if provided)
        if type(mod) == "table" and type(mod.display_name) == "string" then
            set[normalize_string(mod.display_name)] = true
        end
        -- form candidate from key: holy_light_aura -> "holy light aura"
        if type(key) == "string" then
            local candidate = key:gsub("_", " "):gsub("%s+", " ")
            candidate = normalize_string(candidate)
            if candidate ~= "" then set[candidate] = true end
        end
        -- also attempt transforming key to a nicer form (replace underscores with spaces)
        -- and include the raw key as well
        set[normalize_string(key)] = true
    end
    return set
end

local function looks_like_skill_line(line, skill_set)
    -- Heuristic: if normalized line matches known skill names, it's a skill.
    if not line or line == "" then return false end
    local n = normalize_string(line)
    if n == "" then return false end
    if skill_set[n] then return true end
    -- also treat lines with 4+ words as skill names usually (many skill names are 1-3 words)
    local words = 0
    for _ in n:gmatch("%S+") do words = words + 1 end
    if words >= 4 then
        return true
    end
    return false
end

local function parse_blocks(text, spells)
    -- Returns array of { name = <profile_name or nil>, skills = { ... } }
    -- If no explicit headers found, attempt to treat first line as profile name
    -- when it does NOT look like a skill (heuristic).
    if not text or text == "" then return {} end

    local skill_set = build_skill_name_set(spells)
    local blocks = {}
    local current = { name = nil, skills = {} }
    local found_header = false

    local lines = {}
    for line in text:gmatch("[^\r\n]+") do table.insert(lines, trim(line)) end

    -- Quick pass: detect any header anywhere
    for _, l in ipairs(lines) do
        if l ~= "" then
            local hdr = l:match("^%s*[Pp]rofile%s*:%s*(.+)$") or l:match("^%s*%[(.-)%]%s*$")
            if hdr and hdr ~= "" then
                found_header = true
                break
            end
        end
    end

    if not found_header then
        -- No explicit headers: decide whether first non-empty line is a profile name
        local first_nonempty = nil
        for _, l in ipairs(lines) do if l ~= "" then first_nonempty = l; break end end
        if first_nonempty then
            if not looks_like_skill_line(first_nonempty, skill_set) then
                -- Treat first_nonempty as profile name; start from second line for skills
                current.name = trim(first_nonempty)
                local started = false
                for i, l in ipairs(lines) do
                    if l == "" then
                        if #current.skills > 0 then
                            table.insert(blocks, current)
                            current = { name = nil, skills = {} }
                        end
                    else
                        if not started then
                            if l == first_nonempty then
                                started = true
                                goto continue_line
                            end
                        end
                        started = true
                        table.insert(current.skills, l)
                    end
                    ::continue_line::
                end
                if #current.skills > 0 or (current.name and current.name ~= "") then table.insert(blocks, current) end
                return blocks
            end
        end
        -- If we reach here, treat entire file as single block of skills (no name)
        current = { name = nil, skills = {} }
        for _, l in ipairs(lines) do if l ~= "" then table.insert(current.skills, l) end end
        if #current.skills > 0 then table.insert(blocks, current) end
        return blocks
    end

    -- If we have explicit headers, parse normally
    current = { name = nil, skills = {} }
    for _, line in ipairs(lines) do
        local l = trim(line)
        if l == "" then
            if #current.skills > 0 or (current.name and current.name ~= "") then
                table.insert(blocks, current)
                current = { name = nil, skills = {} }
            end
        else
            local header_name = l:match("^%s*[Pp]rofile%s*:%s*(.+)$")
            if not header_name then header_name = l:match("^%s*%[(.-)%]%s*$") end
            if header_name and header_name ~= "" then
                if #current.skills > 0 or (current.name and current.name ~= "") then
                    table.insert(blocks, current)
                end
                current = { name = trim(header_name), skills = {} }
            else
                table.insert(current.skills, l)
            end
        end
    end
    if #current.skills > 0 or (current.name and current.name ~= "") then table.insert(blocks, current) end
    return blocks
end

local function sanitize_profile_name(name)
    if not name or name == "" then return nil end
    local s = name:gsub("[%c%/%\\%:%*%?%\"%<%>%|]", "_")
    s = trim(s)
    if s == "" then return nil end
    return s
end

local function process_blocks(bs, spells)
    local content, err = read_file(IMPORT_FILE_PATH)
    if not content or trim(content) == "" then
        return {}
    end

    local blocks = parse_blocks(content, spells)
    if not blocks or #blocks == 0 then
        return {}
    end

    local results = {}
    for i, block in ipairs(blocks) do
        local prof_name = sanitize_profile_name(block.name)
        if not prof_name then
            -- fallback: use first skill line to craft a friendly name, or timestamp
            local first = (block.skills and block.skills[1]) or nil
            if first and type(first) == "string" then
                -- if first looks like 'Holy Light Aura' use it as part of name
                local candidate = trim(first)
                -- But don't use long skill lines; limit length and sanitize
                candidate = candidate:gsub("[%c%/%\\%:%*%?%\"%<%>%|]", "_")
                candidate = trim(candidate)
                if candidate ~= "" and #candidate <= 40 then
                    prof_name = candidate
                end
            end
        end
        if not prof_name then
            prof_name = "Imported_" .. tostring(os.time()) .. "_" .. tostring(i)
        end

        -- write a temp file with only skill lines (one per line)
        local tmp_ok, tmp_err = write_file(TEMP_IMPORT_PATH, table.concat(block.skills, "\n"))
        if not tmp_ok then
            table.insert(results, { profile = prof_name, ok = false, msg = "Failed to write temp file: " .. tostring(tmp_err) })
        else
            local ok, res_or_msg = pcall(function() return bs.import_from_file(TEMP_IMPORT_PATH, prof_name, spells) end)
            if not ok then
                table.insert(results, { profile = prof_name, ok = false, msg = "Runtime error during import: " .. tostring(res_or_msg) })
            else
                table.insert(results, { profile = prof_name, ok = true, msg = tostring(res_or_msg) })
            end
            pcall(function() os.remove(TEMP_IMPORT_PATH) end)
        end
    end

    pcall(function() clear_file(IMPORT_FILE_PATH) end)
    return results
end

-- updater: wait for build_saver then process once (with retries)
local attempts_since_start = 0
local function updater()
    if done then return end
    local now = (type(get_time_since_inject) == "function") and get_time_since_inject() or os.time()
    if (now - started_at) < WAIT_SECONDS_BEFORE_START then return end

    attempts = attempts + 1
    if attempts > MAX_ATTEMPTS then done = true; return end

    local ok_req, bs = pcall(require, "build_saver")
    if not ok_req or not bs then
        -- keep waiting
        return
    end

    local content, ferr = read_file(IMPORT_FILE_PATH)
    if not content or trim(content) == "" then
        -- nothing to import
        return
    end

    safe_print("import_runner: detected import file; parsing and creating profiles...")
    local ok_proc, results_or_err = pcall(function() return process_blocks(bs, _G and _G.spells or nil) end)
    if not ok_proc then
        safe_print("import_runner: unexpected error while processing import file: " .. tostring(results_or_err))
        done = true
        return
    end

    local results = results_or_err
    if type(results) ~= "table" then
        safe_print("import_runner: processing returned unexpected type; aborting")
        done = true
        return
    end

    for _, r in ipairs(results) do
        if r.ok then
            safe_print("import_runner: imported profile '" .. tostring(r.profile) .. "': " .. tostring(r.msg))
        else
            safe_print("import_runner: FAILED importing profile '" .. tostring(r.profile) .. "': " .. tostring(r.msg))
        end
    end

    done = true
end

if type(on_update) == "function" then
    on_update(function() updater() end)
else
    pcall(function() updater() end)
end

return {}